### PR TITLE
Add Member#getEffectiveNickname()

### PR DESCRIPTION
**Pull request by AlexCai2019**
[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

- Change the current Member#getEffectiveName() to Member#getEffectiveNickname().
- Add Member#getEffectiveName() which works just as same as User#getEffectiveName().
- Use ternary operator in Member#getTimeJoined() because why not.

### CODE REVIEW

**Comment by Andre601** [comment]
I also can't see the logic behind this... A Member can't have more than 1 nickname. And `getEffectiveName()` does iirc this logic:
```
Member has Nickname? -- Yes --> Return Nickname
  |
  |
  V
Member has global Displayname? -- Yes --> Return global display name
  |
  |
  V
Return username/identifier
```

**Comment by MinnDevelopment** [comment]
What is the use-case for this?

**Comment by AlexCai2019** [comment]
Because I think the `getEffectiveName()` method in both `User` and `Member` should return the same thing, which is the global name if present or the name, in order to prevent misuse.
On the other hand, `Member#getEffectiveNickname()` can provide the replaced function of the original `Member#getEffectiveName()`.

**Comment by Andre601** [comment]
> Because I think the `getEffectiveName()` method in both `User` and `Member` should return the same thing, which is the global name if present or the name, in order to prevent misuse. On the other hand, `Member#getEffectiveNickname()` can provide the replaced function of the original `Member#getEffectiveName()`.

I think you missunderstand the logic of `getEffectiveName()` here.

Imagine it as what the bot would "see" when either looking at a User in DMs or a User on a Server.
After all, if a user has a nickname on the server do you see that and not their nickname right? That's the "effective" name they have here.

**Comment by MinnDevelopment** [comment]
The point of `getEffectiveName` is to return the visible name. In the context of a user this is the globally visible name (what you see in DMs) and in the context of a member this is the guild name (visible in the member list of a guild). As such, the returned names are consistent between the two contexts.

Adding another name getter is only adding more confusion and should be avoided. Delegating getters from User into Member is a non-goal. To use the user getters, use `getUser().getXYZ()` instead.

**Pull request closed without merging**
